US_STATE_CODES = [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "DC",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
    "PR",
    "VI",
]

STATE_TIMEZONES = {
    "AL": "America/Chicago",
    "AK": "America/Anchorage",
    "AZ": "America/Phoenix",
    "AR": "America/Chicago",
    "CA": "America/Los_Angeles",
    "CO": "America/Denver",
    "CT": "America/New_York",
    "DE": "America/New_York",
    "DC": "America/New_York",
    "FL": "America/New_York",
    "GA": "America/New_York",
    "HI": "Pacific/Honolulu",
    "ID": "America/Boise",
    "IL": "America/Chicago",
    "IN": "America/Indiana/Indianapolis",
    "IA": "America/Chicago",
    "KS": "America/Chicago",
    "KY": "America/New_York",
    "LA": "America/Chicago",
    "ME": "America/New_York",
    "MD": "America/New_York",
    "MA": "America/New_York",
    "MI": "America/Detroit",
    "MN": "America/Chicago",
    "MS": "America/Chicago",
    "MO": "America/Chicago",
    "MT": "America/Denver",
    "NE": "America/Chicago",
    "NV": "America/Los_Angeles",
    "NH": "America/New_York",
    "NJ": "America/New_York",
    "NM": "America/Denver",
    "NY": "America/New_York",
    "NC": "America/New_York",
    "ND": "America/Chicago",
    "OH": "America/New_York",
    "OK": "America/Chicago",
    "OR": "America/Los_Angeles",
    "PA": "America/New_York",
    "RI": "America/New_York",
    "SC": "America/New_York",
    "SD": "America/Chicago",
    "TN": "America/Chicago",
    "TX": "America/Chicago",
    "UT": "America/Denver",
    "VT": "America/New_York",
    "VA": "America/New_York",
    "WA": "America/Los_Angeles",
    "WV": "America/New_York",
    "WI": "America/Chicago",
    "WY": "America/Denver",
    "PR": "America/Puerto_Rico",
    "VI": "America/St_Thomas",
}

HOURLY_COLUMN_RENAMES = {
    "stateCode": "State",
    "facilityName": "Facility Name",
    "facilityId": "Facility ID",
    "unitId": "Unit ID",
    "unit_id": "Unit ID 2",
    "associatedStacks": "Associated Stacks",
    "opTime": "Op Time",
    "grossLoad": "Gross Load",
    "steamLoad": "Steam Load",
    "so2Mass": "SO2 Mass",
    "so2Rate": "SO2 Rate",
    "co2Mass": "CO2 Mass",
    "co2MassMeasureFlg": "CO2 Mass Measure Flag",
    "co2Rate": "CO2 Rate",
    "co2RateMeasureFlg": "CO2 Rate Measure Flag",
    "noxMass": "NOx Mass",
    "noxMassMeasureFlg": "NOx Mass Measure Flag",
    "noxRate": "NOx Rate",
    "noxRateMeasureFlg": "NOx Rate Measure Flag",
    "heatInput": "Heat Input",
    "heatInputMeasureFlg": "Heat Input Measure Flag",
    "primaryFuelInfo": "Primary Fuel Info",
    "secondaryFuelInfo": "Secondary Fuel Info",
    "unitType": "Unit Type",
    "so2ControlInfo": "SO2 Control Info",
    "noxControlInfo": "NOx Control Info",
    "pmControlInfo": "PM Control Info",
    "hgControlInfo": "HG Control Info",
    "programCodeInfo": "Program Code Info",
}

ATTRIBUTE_COLUMN_RENAMES = {
    "latitude": "lat",
    "longitude": "lon",
    "county": "County",
    "countyCode": "County Code",
    "fipsCode": "FIPS Code",
    "epaRegion": "EPA Region",
    "nercRegion": "NERC Region",
    "sourceCategory": "Source Category",
    "ownerOperator": "Owner Operator",
    "so2Phase": "SO2 Phase",
    "noxPhase": "NOx Phase",
    "commercialOperationDate": "Commercial Operation Date",
    "operatingStatus": "Operating Status",
    "maxHourlyHIRate": "Max Hourly HI Rate",
    "associatedGeneratorsAndNameplateCapacity": (
        "Associated Generators and Nameplate Capacity"
    ),
}

ATTRIBUTE_COLUMNS = [
    "facilityId",
    "unitId",
    *ATTRIBUTE_COLUMN_RENAMES.keys(),
]

POWER_PLANT_EMISSIONS_GENERATION_COLUMNS = [
    "Interval Start",
    "Interval End",
    "State",
    "Facility Name",
    "Facility ID",
    "Unit ID",
    "Unit ID 2",
    "Associated Stacks",
    "Op Time",
    "Gross Load",
    "Steam Load",
    "SO2 Mass",
    "SO2 Rate",
    "CO2 Mass",
    "CO2 Mass Measure Flag",
    "CO2 Rate",
    "CO2 Rate Measure Flag",
    "NOx Mass",
    "NOx Mass Measure Flag",
    "NOx Rate",
    "NOx Rate Measure Flag",
    "Heat Input",
    "Heat Input Measure Flag",
    "Primary Fuel Info",
    "Secondary Fuel Info",
    "Unit Type",
    "SO2 Control Info",
    "NOx Control Info",
    "PM Control Info",
    "HG Control Info",
    "Program Code Info",
    "lat",
    "lon",
    "County",
    "County Code",
    "FIPS Code",
    "EPA Region",
    "NERC Region",
    "Source Category",
    "Owner Operator",
    "SO2 Phase",
    "NOx Phase",
    "Commercial Operation Date",
    "Operating Status",
    "Max Hourly HI Rate",
    "Associated Generators and Nameplate Capacity",
]
