OPERATING_POWER_PLANT_COLUMNS = [
    "Period",
    "Entity ID",
    "Entity Name",
    "Plant ID",
    "Plant Name",
    "Plant State",
    "County",
    "Balancing Authority Code",
    "Sector",
    "Generator ID",
    "Unit Code",
    "Nameplate Capacity",
    "Net Summer Capacity",
    "Net Winter Capacity",
    "Technology",
    "Energy Source Code",
    "Prime Mover Code",
    "Operating Month",
    "Operating Year",
    "Planned Retirement Month",
    "Planned Retirement Year",
    "Status",
    "Nameplate Energy Capacity",
    "DC Net Capacity",
    "Planned Derate Year",
    "Planned Derate Month",
    "Planned Derate of Summer Capacity",
    "Planned Uprate Year",
    "Planned Uprate Month",
    "Planned Uprate of Summer Capacity",
    "Latitude",
    "Longitude",
]

PLANNED_POWER_PLANT_COLUMNS = [
    "Period",
    "Entity ID",
    "Entity Name",
    "Plant ID",
    "Plant Name",
    "Plant State",
    "County",
    "Balancing Authority Code",
    "Sector",
    "Generator ID",
    "Unit Code",
    "Nameplate Capacity",
    "Net Summer Capacity",
    "Net Winter Capacity",
    "Technology",
    "Energy Source Code",
    "Prime Mover Code",
    "Planned Operation Month",
    "Planned Operation Year",
    "Status",
    "Latitude",
    "Longitude",
]

RETIRED_POWER_PLANT_COLUMNS = [
    "Period",
    "Entity ID",
    "Entity Name",
    "Plant ID",
    "Plant Name",
    "Plant State",
    "County",
    "Balancing Authority Code",
    "Sector",
    "Generator ID",
    "Unit Code",
    "Nameplate Capacity",
    "Net Summer Capacity",
    "Net Winter Capacity",
    "Technology",
    "Energy Source Code",
    "Prime Mover Code",
    "Operating Month",
    "Operating Year",
    "Retirement Month",
    "Retirement Year",
    "Nameplate Energy Capacity",
    "DC Net Capacity",
    "Latitude",
    "Longitude",
]

CANCELED_OR_POSTPONED_POWER_PLANT_COLUMNS = [
    "Period",
    "Entity ID",
    "Entity Name",
    "Plant ID",
    "Plant Name",
    "Plant State",
    "County",
    "Balancing Authority Code",
    "Sector",
    "Generator ID",
    "Unit Code",
    "Nameplate Capacity",
    "Net Summer Capacity",
    "Net Winter Capacity",
    "Technology",
    "Energy Source Code",
    "Prime Mover Code",
    "Latitude",
    "Longitude",
]
