WIND_ACTUAL_AND_FORECAST_COLUMNS = [
    "Interval Start",
    "Interval End",
    "Publish Time",
    "GEN SYSTEM WIDE",
    "COP HSL SYSTEM WIDE",
    "STWPF SYSTEM WIDE",
    "WGRPP SYSTEM WIDE",
    "HSL SYSTEM WIDE",
    "GEN LZ SOUTH HOUSTON",
    "COP HSL LZ SOUTH HOUSTON",
    "STWPF LZ SOUTH HOUSTON",
    "WGRPP LZ SOUTH HOUSTON",
    "GEN LZ WEST",
    "COP HSL LZ WEST",
    "STWPF LZ WEST",
    "WGRPP LZ WEST",
    "GEN LZ NORTH",
    "COP HSL LZ NORTH",
    "STWPF LZ NORTH",
    "WGRPP LZ NORTH",
]

WIND_ACTUAL_AND_FORECAST_BY_GEOGRAPHICAL_REGION_COLUMNS = [
    "Interval Start",
    "Interval End",
    "Publish Time",
    "GEN SYSTEM WIDE",
    "COP HSL SYSTEM WIDE",
    "STWPF SYSTEM WIDE",
    "WGRPP SYSTEM WIDE",
    "HSL SYSTEM WIDE",
    "GEN PANHANDLE",
    "COP HSL PANHANDLE",
    "STWPF PANHANDLE",
    "WGRPP PANHANDLE",
    "GEN COASTAL",
    "COP HSL COASTAL",
    "STWPF COASTAL",
    "WGRPP COASTAL",
    "GEN SOUTH",
    "COP HSL SOUTH",
    "STWPF SOUTH",
    "WGRPP SOUTH",
    "GEN WEST",
    "COP HSL WEST",
    "STWPF WEST",
    "WGRPP WEST",
    "GEN NORTH",
    "COP HSL NORTH",
    "STWPF NORTH",
    "WGRPP NORTH",
]

SOLAR_ACTUAL_AND_FORECAST_COLUMNS = [
    "Interval Start",
    "Interval End",
    "Publish Time",
    "GEN SYSTEM WIDE",
    "COP HSL SYSTEM WIDE",
    "STPPF SYSTEM WIDE",
    "PVGRPP SYSTEM WIDE",
    "HSL SYSTEM WIDE",
]

SOLAR_ACTUAL_AND_FORECAST_BY_GEOGRAPHICAL_REGION_COLUMNS = [
    "Interval Start",
    "Interval End",
    "Publish Time",
    "GEN SYSTEM WIDE",
    "COP HSL SYSTEM WIDE",
    "STPPF SYSTEM WIDE",
    "PVGRPP SYSTEM WIDE",
    "HSL SYSTEM WIDE",
    "GEN CenterWest",
    "COP HSL CenterWest",
    "STPPF CenterWest",
    "PVGRPP CenterWest",
    "GEN NorthWest",
    "COP HSL NorthWest",
    "STPPF NorthWest",
    "PVGRPP NorthWest",
    "GEN FarWest",
    "COP HSL FarWest",
    "STPPF FarWest",
    "PVGRPP FarWest",
    "GEN FarEast",
    "COP HSL FarEast",
    "STPPF FarEast",
    "PVGRPP FarEast",
    "GEN SouthEast",
    "COP HSL SouthEast",
    "STPPF SouthEast",
    "PVGRPP SouthEast",
    "GEN CenterEast",
    "COP HSL CenterEast",
    "STPPF CenterEast",
    "PVGRPP CenterEast",
]
