WIND_ACTUAL_AND_FORECAST_COLUMNS = [
    "Interval Start",
    "Interval End",
    "Publish Time",
    "GEN SYSTEM WIDE",
    "COP HSL SYSTEM WIDE",
    "STWPF SYSTEM WIDE",
    "WGRPP SYSTEM WIDE",
    "HSL SYSTEM WIDE",
    "GEN LZ SOUTH HOUSTON",
    "COP HSL LZ SOUTH HOUSTON",
    "STWPF LZ SOUTH HOUSTON",
    "WGRPP LZ SOUTH HOUSTON",
    "GEN LZ WEST",
    "COP HSL LZ WEST",
    "STWPF LZ WEST",
    "WGRPP LZ WEST",
    "GEN LZ NORTH",
    "COP HSL LZ NORTH",
    "STWPF LZ NORTH",
    "WGRPP LZ NORTH",
]

WIND_ACTUAL_AND_FORECAST_BY_GEOGRAPHICAL_REGION_COLUMNS = [
    "Interval Start",
    "Interval End",
    "Publish Time",
    "GEN SYSTEM WIDE",
    "COP HSL SYSTEM WIDE",
    "STWPF SYSTEM WIDE",
    "WGRPP SYSTEM WIDE",
    "HSL SYSTEM WIDE",
    "GEN PANHANDLE",
    "COP HSL PANHANDLE",
    "STWPF PANHANDLE",
    "WGRPP PANHANDLE",
    "GEN COASTAL",
    "COP HSL COASTAL",
    "STWPF COASTAL",
    "WGRPP COASTAL",
    "GEN SOUTH",
    "COP HSL SOUTH",
    "STWPF SOUTH",
    "WGRPP SOUTH",
    "GEN WEST",
    "COP HSL WEST",
    "STWPF WEST",
    "WGRPP WEST",
    "GEN NORTH",
    "COP HSL NORTH",
    "STWPF NORTH",
    "WGRPP NORTH",
]

SOLAR_ACTUAL_AND_FORECAST_COLUMNS = [
    "Interval Start",
    "Interval End",
    "Publish Time",
    "GEN SYSTEM WIDE",
    "COP HSL SYSTEM WIDE",
    "STPPF SYSTEM WIDE",
    "PVGRPP SYSTEM WIDE",
    "HSL SYSTEM WIDE",
]

SOLAR_ACTUAL_AND_FORECAST_BY_GEOGRAPHICAL_REGION_COLUMNS = [
    "Interval Start",
    "Interval End",
    "Publish Time",
    "GEN SYSTEM WIDE",
    "COP HSL SYSTEM WIDE",
    "STPPF SYSTEM WIDE",
    "PVGRPP SYSTEM WIDE",
    "HSL SYSTEM WIDE",
    "GEN CenterWest",
    "COP HSL CenterWest",
    "STPPF CenterWest",
    "PVGRPP CenterWest",
    "GEN NorthWest",
    "COP HSL NorthWest",
    "STPPF NorthWest",
    "PVGRPP NorthWest",
    "GEN FarWest",
    "COP HSL FarWest",
    "STPPF FarWest",
    "PVGRPP FarWest",
    "GEN FarEast",
    "COP HSL FarEast",
    "STPPF FarEast",
    "PVGRPP FarEast",
    "GEN SouthEast",
    "COP HSL SouthEast",
    "STPPF SouthEast",
    "PVGRPP SouthEast",
    "GEN CenterEast",
    "COP HSL CenterEast",
    "STPPF CenterEast",
    "PVGRPP CenterEast",
]

SYSTEM_AS_CAPACITY_MONITOR_COLUMNS = [
    "Time",
    "RRS Capability PFR Gen and ESR",
    "RRS Capability Load Ex Controllable Load",
    "RRS Capability PFR Controllable Load",
    "RRS Capability FFR Capable Ex ESR",
    "RRS Capability FFR ESR",
    "RRS Awards PFR Gen and ESR",
    "RRS Awards UFR Load Ex Controllable Load",
    "RRS Awards PFR Controllable Load",
    "RRS Awards FFR Capable",
    "ECRS Capability Gen",
    "ECRS Capability Load Ex Controllable Load",
    "ECRS Capability Controllable Load",
    "ECRS Capability Quick Start Gen",
    "ECRS Capability ESR",
    "ECRS Capability Manually Deployed ONSC Status",
    "ECRS Awards Gen",
    "ECRS Awards Load Ex Controllable Load",
    "ECRS Awards Controllable Load",
    "ECRS Awards Quick Start Gen",
    "ECRS Awards ESR",
    "Nspin Capability On Line Gen with Energy Offers",
    "Nspin Capability Resources with Output Schedules",
    "Nspin Capability Undeployed Load",
    "Nspin Capability Offline Gen Ex QSGR Online Gen with power aug",
    "Nspin Capability ESR",
    "NSpin Awards On Line Gen with Energy Offer Curves",
    "NSpin Awards On Line Gen with Output Schedules",
    "NSPin Awards Load",
    "NSpin Awards Offline Gen Ex QSGR Including power aug",
    "NSpin Awards Quick Start Gen",
    "NSpin Awards ESR",
    "Reg Capability Reg Up",
    "Reg Capability Reg Down",
    "Reg Capability Undeployed Reg Up",
    "Reg Capability Undeployed Reg Down",
    "Reg Capability Deployed Reg Up",
    "Reg Capability Deployed Reg Down",
    "Reg Awards Reg Up",
    "Reg Awards Reg Down",
    "Capacity From CLRS Available To Decrease Base Points In SCED",
    "Capacity From CLRS Available To Increase Base Points In SCED",
    "Capacity With Energy Offer Curves To Increase Genres BP In SCED",
    "Capacity With Energy Offer Curves To Decrease Genres BP In SCED",
    "Capacity Without Energy Offers To Increase Genres BP In SCED",
    "Capacity Without Energy Offers To Decrease Genres BP In SCED",
    "Capacity with energy offers to increase ESR BP in SCED",
    "Capacity with energy offers to decrease ESR BP in SCED",
    "Capacity without energy offers to increase ESR BP in SCED",
    "Capacity without energy offers to decrease ESR BP in SCED",
    "Capacity To Increase Genres BP In Next Five Minutes In SCED HDL",
    "Capacity To Decrease Genres BP In Next Five Minutes In SCED LDL",
    "Capacity to provide Reg Up RRS or Both",
    "Capacity to provide Reg Up RRS ECRS or any combo",
    "Capacity to provide Reg Up RRS ECRS NSpin any combination",
    "PRC",
    "ORDC Online",
    "ORDC Online and Offline",
    "Telemetered HSL Capacity Resource Status EMR",
    "Telemetered HSL Capacity Resource Status OUT",
    "Telemetered Net Consumption Resource status OUTL",
]
