name: Build Docs
on: [pull_request]
jobs:
  build_docs:
    name: ${{ matrix.python_version }} build docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.11"]
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install gridstatus
        run: poetry install
      - name: Build docs
        run: make docs
