name: Build Docs
on: [pull_request]
jobs:
  build_docs:
    name: 3.10 build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pip
          key: py-3.10-docs-${{ hashFiles('pyproject.toml') }}-v01
          restore-keys: |
            py-3.10-docs-
      - name: Build gridstatus package and install docs deps (if cache has not changed)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          make package
          python -m pip install "unpacked/[docs]"
      - name: Build docs
        run: make docs
