name: Build Docs
on: [pull_request]
jobs:
  build_docs:
    name: 3.10 build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pip
          key: py-3.10-docs-${{ hashFiles('pyproject.toml') }}-v01
          restore-keys: |
            py-3.10-docs-
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Build gridstatus package
        run: make package
      - name: Install gridstatus
        run: python -m pip install "unpacked/[docs]"
      - name: Build docs
        run: make docs
