on:
  release:
    types: [published]

name: Build and Release
jobs:
  pypi-release:
    runs-on: ubuntu-latest
    # Uses trusted published from GitHub Actions. No need
    # for credentials or API tokens.
    # https://docs.pypi.org/trusted-publishers/using-a-publisher/
    environment:
      name: pypi
      url: https://pypi.org/p/gridstatus
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Check version match
      run: |
        PACKAGE_VERSION=$(uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version)
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
          echo "Package version ($PACKAGE_VERSION) does not match tag version ($TAG_VERSION)"
          exit 1
        fi

    - name: Install dependencies
      run: uv sync

    - name: Build package
      run: uv build

    # https://github.com/pypa/gh-action-pypi-publish
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
