name: Test ISONE API
on: # Run on all pushes and pull requests
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    env:
      ISONE_API_USERNAME: ${{ secrets.ISONE_API_KEY }}
      ISONE_API_PASSWORD: ${{ secrets.ISONE_API_PASSWORD }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v3.1.7

      - name: Install dependencies
        run: |
          uv pip install vcrpy

      - name: Echo Environment Variables
        run: |
          echo "Checking if environment variables are set:"
          if [ -n "$ISONE_API_USERNAME" ]; then echo "ISONE_API_USERNAME is set"; else echo "ISONE_API_USERNAME is not set"; fi
          if [ -n "$ISONE_API_PASSWORD" ]; then echo "ISONE_API_PASSWORD is set"; else echo "ISONE_API_PASSWORD is not set"; fi

      - name: Run unit tests without coverage
        if: ${{ matrix.python-version != '3.11' }}
        run: |
          uv run pytest -v gridstatus/tests/test_isone_api.py
